//
// Created by azbest on 16.12.17.
//

#ifndef LAB678_UNSUPPORTEDOPERATIONEXCEPTION_H
#define LAB678_UNSUPPORTEDOPERATIONEXCEPTION_H


class UnsupportedOperationException {

};


#endif //LAB678_UNSUPPORTEDOPERATIONEXCEPTION_H
